### ISSUE TITLE
[Code Fix] Removed redundant condition

### ISSUE THREAD

**Issue by e6654321** [ton-blockchain/wallet-contract-v5#14]
#13 - Removed unnecessary conditional when going through the progress actions

**Comment by nns2009** [comment]
Gotta be careful with it since `|` is not lazy in FunC (and neither is in C++), although upon further inspection, it looks like possible optimization since when the expected behavior is to add extension (`is_add_extension` is true), the only way for `cs~check_and_remove_remove_extension_prefix()` to also pass would be for the (requesting-to-add) Extension address to be [addr_none](https://github.com/ton-blockchain/ton/blob/5c392e0f2d946877bb79a09ed35068f7b0bd333a/crypto/block/block.tlb#L100) (followed by `000011` extra bits), and adding `addr_none` extension won't pass `parse_std_addr` of the next line anyway.

Users would also be able to do 'add' by inserting extra 0x03 into add-action: 0x0203\<address> instead of 0x02\<address>.

None of these seems to lead to any issues, but it would need to be thoroughly rechecked just in case.

**Comment by tolya-yanot** [comment]
Wrong suggestion
